### PR TITLE
Export make template functions

### LINKED ISSUE #16: Use chalk-template with a custom chalk instance
Taking a quick look at the code, I don’t think this is possible currently.

It would be helpful if both `makeTemplate` and `makeChalkTemplate` were exported so I could do the following:

```js
import {Chalk} from 'chalk'
import {makeTemplate, makeChalkTemplate} from 'chalk-template'

const chalk = new Chalk({ level: 0  })
const chalkTemplate = makeChalkTemplate(makeTemplate(chalk))

console.log(chalkTemplate`{red Hi!}`)
```

The code above should print `Hi!` with no coloring. This is a silly example, but I would like a way to write strings with predefined colors and also be able to pass those strings to a template function that would remove them. This would also be possible by using the regexes in the source to strip colors, but the way in my example seems easier to write.

Also for my use case, I would want to use both functions together, so a single export that wraps `makeChalkTemplate(makeTemplate())` would be nice, but not required.

### PR DESCRIPTION
**Pull request by lukekarrys**
The only source changes were to export the two existing functions. I tried to add tests and docs to match the existing style. The resulting `d.ts` file isn't very DRY, I can clean that up if necessary.

Closes #16

### CODE REVIEW

**Comment by Qix-** [comment]
Meh the names of those functions kind of rub me the wrong way. Maybe we can improve the names while we're at it. I'll think about it overnight but if you have any ideas feel free to suggest them.

Thanks for the PR :)

**Comment by lukekarrys** [comment]
I'll agree to the names of the functions not being ideal for public consumption. But I don't have any better names off the top of my head.

I marked this PR as allowing edits from maintainers, so feel free to update if you come up with better names.

**Comment by Qix-** [comment]
Instead of exporting `makeChalkTemplate` directly, do you mind instead making a new function called `makeTaggedTemplate` that does essentially `chalk => makeChalkTemplate(makeTemplate(chalk))`?

The net effect being that we export `makeTemplate` which returns just a string->string function, and `makeTaggedTemplate` that is a tagged template function, both of which take a `Chalk` instance.

**Comment by lukekarrys** [comment]
Those suggestion have been implemented. Both functions now take a `Chalk` instance. Types and tests have been updated as well.

**Comment by lukekarrys** [comment]
Hey @Qix-, friendly ping on this one 😄 

My plan was to use this feature once I've landed `chalk@5` (https://github.com/npm/cli/pull/6285) which I am slowly working towards. So no rush! Excited for this since once we are on `chalk@5` this feature will be a huge help for us.

**Pull request merged**
